set(MATLIB_CMAKE_PATH ${CMAKE_CURRENT_LIST_DIR} CACHE STRING "Matlib installation path")
message("Loading matlib lists from ${MATLIB_CMAKE_PATH}")



option(USE_PK "Build for use with the RISCV Proxy Kernel" OFF)
option(USE_CPU "Use CPU implementation" OFF)
option(USE_GEMMINI "Use Gemmini implementation" OFF)
option(USE_RVV "Use RISCV vector extension implementation" OFF)
option(USE_HANDOPT "Use RISCV vector extension implementation" OFF)
option(USE_RVVU "Use RISCV vector extension unrolling optimizations" OFF)
option(USE_RVA "Use RISCV vector extension array implementation" OFF)
option(USE_MATVEC "Use matvec instead of matmul for matrix multiplication" ON)
option(MEMORY "Use Memory Optimizations" ON)
option(CHECKSUM "Use checksum to debug component functions" OFF)
option(OPTIMIZED "Use Extra Optimizations" ON)
option(MEASURE_CYCLES "Measure Cycles" OFF)
option(MATLIB_EXTERNAL_BUILD "If matlib is built by an external project" OFF)

set(USE_LMUL "1" CACHE STRING "LMUL to use in vector instructions")
add_compile_definitions(USE_LMUL=${USE_LMUL})

if(USE_PK)
    add_compile_definitions(USE_PK=1)
endif(USE_PK)
if(USE_CPU)
    add_compile_definitions(USE_CPU=1)
endif(USE_CPU)
if(USE_GEMMINI)
    add_compile_definitions(USE_GEMMINI=1)
endif(USE_GEMMINI)
if(USE_RVV)
    add_compile_definitions(USE_RVV=1)
endif(USE_RVV)
if(USE_HANDOPT)
    add_compile_definitions(USE_HANDOPT=1)
endif(USE_HANDOPT)
if(USE_RVVU)
    add_compile_definitions(USE_RVVU=1)
endif(USE_RVVU)
if(USE_RVA)
    add_compile_definitions(USE_RVA=1)
endif(USE_RVA)
if(USE_MATVEC)
    add_compile_definitions(USE_MATVEC=1)
endif(USE_MATVEC)
if(MEMORY)
    add_compile_definitions(MEMORY=1)
endif(MEMORY)
if(CHECKSUM)
    add_compile_definitions(TRACE_CHECKSUMS=1)
endif(CHECKSUM)
if(OPTIMIZED)
    add_compile_definitions(OPTIMIZED=1)
endif(OPTIMIZED)
if(MEASURE_CYCLES)
    add_compile_definitions(MEASURE_CYCLES=1)
endif(MEASURE_CYCLES)


